spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_textile_industry?useUnicode=true&characterEncoding=utf-8&serverTimezone = GMT%2B8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  resources:
    static-locations: classpath:/static


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.ndky.WaterFDS.pojo
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full


server:
  servlet:
    context-path: /WaterFDS


